### ISSUE TITLE
是否使用了 滴答清单 API

### ISSUE THREAD

**Issue by Sciroccogti** [vcjmhg/GDTHelper#6]
我注意到本项目似乎没有用到 [滴答清单 API](https://developer.dida365.com/docs/index.html#/openapi)，不知情况是否真的如此。

（本来想来学习一下怎么调用 API 的 orz

**Comment by vcjmhg** [comment]
你好，我之前在开发这个demo的时候，官方还没有提供API，当时是直接通过web后台接口来获取接口的。官方API是最近才开始公开的，并且当前滴答清单的统计功能已经很强大了，所有这边这个demo就暂时停止了哈。
```java
 StringBuilder diDaJsonUrl=new StringBuilder("https://api.dida365.com/api/v2/project/all/completedInAll/");
 diDaJsonUrl.append("?from="+fromTime);
 diDaJsonUrl.append("&to="+toTime);
 diDaJsonUrl.append("%2023:26:45&limit="+limit);
```

**Comment by Sciroccogti** [comment]
非常感谢！
